Fundamentals of tensorflow

In [42]:
import tensorflow as tf
print(tf.__version__)

2.18.0


In [3]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
#no of dimensiuons of a tensor
scalar.ndim

0

In [6]:
#Create  a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [7]:
#check the dimension of vector 
vector.ndim

1

In [9]:
#Create a Matrix
matrix = tf.constant([[10,7],[11,7]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [11,  7]])>

In [10]:
matrix.ndim

2

In [15]:
##Create another mat
an_mat = tf.constant([[10.,5.],
                     [3.,2.],
                     [4.,5.]],dtype = tf.float16)
an_mat#16,31 matlab ki jo no hai wo memory mai kaam space leke store honge agr 16 htoh 32 h toh thoda zyda
#if we get error ahead of wrong data type we will change data type using dtype

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  5.],
       [ 3.,  2.],
       [ 4.,  5.]], dtype=float16)>

In [16]:
an_mat.ndim

2

In [32]:


tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]],
                      [[19, 14, 15],
                       [13, 18, 22]]])  # Fixed the missing comma

tensor


<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[19, 14, 15],
        [13, 18, 22]]])>

In [33]:
tensor.ndim#3 dimensions hai iske

3

In [38]:
##creating with tf.variable()
chang_tensor = tf.Variable([10,7])
umchang_tensor = tf.constant([10,7])
chang_tensor,umchang_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>)

In [39]:
#change one of the elements in our changeable tensor
chang_tensor[0] = 7
chang_tensor

TypeError: 'ResourceVariable' object does not support item assignment

In [41]:
##try .assign()
chang_tensor[0].assign(7)
chang_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7])>

In [43]:
umchang_tensor[0].assign(7)

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

In [50]:
#create two random tensors 
random_1 = tf.random.Generator.from_seed(42)
 #set seed for reproducibility
random_1 = random_1.normal(shape=(3,2))
random_1
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))
random_2
random_2,random_1,random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [9]:
not_shuffled = tf.constant([[10,7],
                           [23,7],
                           [5,7]])
not_shuffled.ndim
#shiuffle our non shuffled tensor
shuffled = tf.random.shuffle(not_shuffled,seed= 42)

In [10]:
not_shuffled
shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 5,  7],
       [23,  7],
       [10,  7]])>

In [15]:
tf.random.set_seed(seed = 42)#global level random seed
tf.random.shuffle(not_shuffled,seed = 42)#operational level random seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [23,  7],
       [ 5,  7]])>

In [16]:
###other ways to make tensors
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [18]:
#create a tensor of all zeroes
tensor = tf.zeros([10,7])
tensor

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [21]:
#we can turn numpy arr to tensors
import numpy as np 
arr = np.arange(1,25,dtype=np.int32)
arr #arr btw 1 to 25

# X = tf.constant(matrix) #capital for Matrix and non capital for vector 
# y = tf.constant(vector)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [25]:
A = tf.constant(arr,shape = (2,3,4))
B = tf.constant(arr)
A,B#convert it into tensor

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24])>)

Getting Information from tensors


In [27]:
ten = tf.zeros([2,3,4,5])
ten

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [28]:
ten[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [30]:
ten.shape,ten.ndim,tf.size(ten)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [41]:
print("Datatype of every ele:",ten.dtype)
print("Shape of every ele:",ten.shape)
print("No of dim (rank) of every ten:",ten.ndim)
print("Shape of Tensor:",ten.shape)
print("Elements along 0th axis:",ten.shape[0])
print("Elements along last axis:",ten.shape[-1])
print("total no of elements:",int(tf.size(ten)))
#print("total no of elements:",tf.size(ten).numpy())

Datatype of every ele: <dtype: 'float32'>
Shape of every ele: (2, 3, 4, 5)
No of dim (rank) of every ten: 4
Shape of Tensor: (2, 3, 4, 5)
Elements along 0th axis: 2
Elements along last axis: 5
total no of elements: 120
total no of elements: 120


In [44]:
ten1 = tf.zeros(shape=[2,3,4,5])
ten1

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [45]:
ten1[:2,:2,:2,:2]#just like list 

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [46]:
#get first ele from each dim except last one 
ten1[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [51]:
ten2 = tf.constant([[10,7],
                    [3,2]])
ten2.ndim

2

In [52]:
list = [1,2,34,4]
list,list[-1]

([1, 2, 34, 4], 4)

In [53]:
#get the last item of each row
ten2[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 2])>

In [57]:
##add a extra dim to rank 2 tensor 
rank_3_ten = ten2[...,tf.newaxis]
rank_3_ten

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 2]]])>

In [7]:
import tensorflow as tf
ten2 = tf.constant([[10,7],
                    [3,2]])

In [8]:
ten3 = tf.expand_dims(ten2,axis=-1)
ten3


<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 2]]])>

In [9]:
tf.expand_dims(ten2,axis = 0
)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  2]]])>

## Manupilating Tensors

**Basic addition**

In [62]:
tensor = tf.constant([[10,7],[3,4]])
tensor + 10#abhi og tensors unchanged hai 

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]])>

In [64]:
tf.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]])>

**Matrix Multiplication**


**in ml it a vey basic operation.**


In [11]:
#matirix multiplication in tensorflow
ten7 = ten2+10
ten7

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 12]])>

In [12]:
tenn = tf.matmul(ten2,ten7)
tenn

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[291, 254],
       [ 86,  75]])>

In [14]:
ten2*ten7#diff o/p as it is a element wise multiplication

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[200, 119],
       [ 39,  24]])>

In [15]:
#Create tensor of (3,2)
X = tf.constant([[1,2],
                 [3,4],
                  [5,6]])
#Create another (3,2)
Y = tf.constant([[11,12],
                 [8,8],
                 [9,7]])
#Try to matirx multiyply the tensors


In [16]:
tf.matmul(X,Y)

InvalidArgumentError: {{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:CPU:0}} Matrix size-incompatible: In[0]: [3,2], In[1]: [3,2] [Op:MatMul] name: 

In [17]:
tf.transpose(ten7)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 13],
       [17, 12]])>

In [18]:
#perform the dot product on X and Y(requires x or y to be transposed bcoz the dim should be same).
tf.tensordot(tf.transpose(X),Y,axes = 1) 

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 80,  71],
       [108,  98]])>

In [23]:
tf.tensordot(tf.transpose(X),Y,axes = 0)

<tf.Tensor: shape=(2, 3, 3, 2), dtype=int32, numpy=
array([[[[11, 12],
         [ 8,  8],
         [ 9,  7]],

        [[33, 36],
         [24, 24],
         [27, 21]],

        [[55, 60],
         [40, 40],
         [45, 35]]],


       [[[22, 24],
         [16, 16],
         [18, 14]],

        [[44, 48],
         [32, 32],
         [36, 28]],

        [[66, 72],
         [48, 48],
         [54, 42]]]])>

In [24]:
tf.matmul(X,tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 35,  24,  23],
       [ 81,  56,  55],
       [127,  88,  87]])>

In [26]:
tf.matmul(X,tf.reshape(Y,shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  22],
       [ 65,  72,  52],
       [103, 114,  82]])>

## Changing the data type of tensors

In [28]:
B = tf.constant([1,7,7.4])
B

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1. , 7. , 7.4], dtype=float32)>

In [29]:
B = tf.cast(B,dtype = tf.float16)

In [30]:
B

<tf.Tensor: shape=(3,), dtype=float16, numpy=array([1. , 7. , 7.4], dtype=float16)>

## Aggregating Tensors

In [32]:
##condensing them from multiple values to a smaller amount of values.
#get the absolute value
import tensorflow as tf
D = tf.constant([-7,-10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10])>

In [33]:
#get th abs value
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10])>

In [34]:
import numpy as np 
C = tf.constant(np.random.randint(0,100,size = 50))

In [35]:
C

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([29, 44, 60, 95, 95, 35, 30, 37, 88, 70,  5, 24, 36, 11, 91, 85,  4,
       91, 31, 77, 18, 61, 36, 39, 75, 68, 55, 37,  8, 72, 62, 95, 36, 50,
       89, 88, 53, 18, 51, 16, 47,  2, 97, 88, 26, 74, 60, 53, 14, 33])>